name: healthy_eating_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  cloud_firestore:
  firebase_core:
  firebase_database:
  firebase_storage:

  # Analytics
  appmetrica_plugin: ^3.4.0
  firebase_analytics:
  appsflyer_sdk: ^6.17.8
  apphud:

  app_tracking_transparency:
  flutter_riverpod:
  http:
  flutter_dotenv:
  go_router:



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env